spring:
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: classpath:/static/
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  server:
    port: 8080
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

---
spring:
  config:
    activate:
      on-profile: local
